name: Shell_lint

on: 
  push:
    paths:
      - shell/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4

    - name: Run ShellCheck
        uses: azohra/shell-linter@latest
        with:
          path: "shell"